In [1]:
import numpy as np

In [3]:
np.set_printoptions(suppress=True) #aproxima los valores que los valores muy cercanos a 0 sean 0 directamente

In [4]:
#para un sistema de ecuaciones 3x+y = 1
#2x +y = 1
# resuelva con la matriz inversa
A = np.array([[3,1],[2,1]])
print(A)

[[3 1]
 [2 1]]


In [5]:
B = np.array([[1],[1]])

In [6]:
#Calculamos la inversa
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 1. -1.]
 [-2.  3.]]


In [8]:
#calculando el x
x = inversa_A.dot(B)
print(x)

[[0.]
 [1.]]


In [9]:
#esta inversa se puede utilizar para resolver sistemas de ecuaciones con resultados (Matriz B diferente) 
#siempre y cuando se encuentren en el rango de las ecuaciones de la matriz
#para un sistema de ecuaciones 3x+y = 3
#2x +y = 7
# resuelva con la matriz inversa

In [11]:
sol_2 = inversa_A.dot(np.array([[3],[7]]))
print(sol_2)

[[-4.]
 [15.]]
