In [1]:
import numpy as np

In [ ]:
# #trucos
# Aqui les va un pequeño truco para hacer las aproximaciones a cero.

# Se trata de definir un valor muy pequeño (épsilon) contra el que se comparan los elementos de la matriz y si son menores que él entonces ajustarlos a cero:


# eps= 1e-17
# A[np.abs(A) < eps] = 0
########################
# Una matriz es ortogonal cuando todas sus filas son mutuamente ortonormales y todas sus columnas son mutuamente ortonormales.
# Así mismo, una matriz ortogonal es una matriz cuadrada cuya matriz inversa coincide con su matriz transpuesta.

In [9]:
matrizf=np.array([[1,0,2],
                   [0,1,0],
                   [3,0,1],
                  ])

matriz = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1],
                  ])
print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
#comprobamos que todos los vectores son ortogonales entre si

print(matriz[:,0].dot(matriz[:,1]))
print(matriz[:,0].dot(matriz[:,2]))
print(matriz[:,1].dot(matriz[:,2]))

0
0
0


In [11]:
print(matrizf[:,0])#imprime toda la columna 0
print(matrizf[0,:])#imprime toda la fila 0

[1 0 3]
[1 0 2]


In [8]:
# ahora validamos sus normas
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2])) #ahora podemos asegurar que son ortonormales

1.0
1.0
1.0


In [12]:
# ahora verificamos lo mismo para las filas
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


In [13]:
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [14]:
# una matrzi es ortogonal si todos sus vectores son ortonormales
#la transpuesta de una matriz ortogonal es igual a su inversa

In [15]:
#utilizamos un matriz de rotacion para asegurar una ortogonalidad y demostrar lo anteriormente dicho

In [19]:
A= np.array([
            [np.cos(100), -np.sin(100)],
            [np.sin(100), np.cos(100)],
            ])
print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [20]:
#verificamos las normas
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,0]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [21]:
#ahora verificamos la ortogonalidad
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


In [22]:
A_t = A.T #aqui vemos que se cumple que A.T*A=I
print(A_t.dot(A))
print(A.dot(A_t))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [25]:
#verificamos ahora que la inversa sea igual a la transpuesta
A_inv = np.linalg.inv(A)
print(A_inv)
print(A_t)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]
[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [26]:
print(1/A_t.dot(A)) #en este caso la operacion no esta definida python ya corrigio un error en el que 
                    #al hacer esta operacion daban numeros muy grandes pero no me informaba que eran inf y que la operacion no 
                    #esta definida

[[ 1. inf]
 [inf  1.]]


<ipython-input-26-94fb82fa3646>:1: RuntimeWarning: divide by zero encountered in true_divide
  print(1/A_t.dot(A))
