In [2]:
#Para que un sistema de ecuaciones lineales tenga solucion
#la matriz debe ser cuadrada y todos sus vectores linealmente independientes
# no puede tener vectores linealmente dependientes

import numpy as np

In [3]:
A = np.array(
    [
    [0,1,0,0],
    [0,0,1,0],
    [0,1,1,0],
    [1,0,0,1]
    ]
)

In [8]:
#formas de validar si la matriz tiene solucion
#Autovalores o lambdas

# Algo que el profesor no mencionó, aprovechando el cálculo que se hizo es que al hallar los lambdas(valores propios) de la matriz dada, se obtiene:

# [ 1.61803399, -0.61803399, 0, 1 ]
# y otra manera de saber si hay solución única para un sistema de ecuaciones o ver si hay inversa de la matriz, es ver que “cero” no sea un valor propio de la matríz.Luego en este caso la matriz no seria invertible.

lambdas, V = np.linalg.eig(A.T) #esta funcion entrega los lambdas y la matriz V que son expresiones uqe forman la matriz A
# o de las cuales se puede descomponer la matriz A
print(A[lambdas ==0, :])#pedimos que imprimael vector donde los lambdas son iguales a 0

print(lambdas)
print(V)
print(V.dot(lamdas))

[[0 1 1 0]]
[ 1.61803399 -0.61803399  0.          1.        ]
[[ 0.          0.          0.57735027  0.57735027]
 [ 0.52573111  0.85065081  0.57735027  0.        ]
 [ 0.85065081 -0.52573111 -0.57735027 -0.57735027]
 [ 0.          0.          0.          0.57735027]]


NameError: name 'lamdas' is not defined

In [9]:
#nos dijo q la tercer fila tiene un lambda 0 es decir que es linealmente dependiente
np.linalg.inv(A) # es decir que no posee inversa, por esto podemos decir que la matriz es singular pq uno de sus vectores es ld

LinAlgError: Singular matrix