In [1]:
import numpy as np



In [2]:
v = np.array([7,-7,3])
u = np.array([1,1,0])
w = np.array([0,0,1])


In [3]:
print(v.dot(u.T))
print(v.dot(w.T))
print(u.dot(w.T))

0
3
0


In [4]:
vector = np.array([1/2,1/2,1/2,1/2])

In [5]:
np.linalg.norm(vector,2)

1.0

In [6]:
print(v*5)

[ 35 -35  15]


In [7]:
escalar = 3.1

In [8]:
escalar.shape


AttributeError: 'float' object has no attribute 'shape'

In [ ]:
matriz = np.array([[1, 0, 0, 0, 0],
[0, 2, 0, 0, 0],
[0, 0, 3, 0, 0],
[0, 0, 0, 4, 0],
[0, 0, 0, 0, 5]])

In [9]:
np.trace(matriz)
np.linalg.det(matriz)

NameError: name 'matriz' is not defined

In [10]:
a=np.array([[-7, 1],[-3,1]])
b=np.array([2,5])

print(np.linalg.solve(a,b))


[0.75 7.25]


In [16]:
M1 = np.array([[1,-1],
               [0,2]
              ])
M2 = np.array([
            [1,0],
            [1,1]
            ])
print(M1)
print(M2)
print(np.linalg.det(M1)*np.linalg.det(M2))
print(np.linalg.det(M1.dot(M2)))
print(np.linalg.det(M1.dot(M2)) == np.linalg.det(M1)*np.linalg.det(M2))# demostramos que si son lo mismo ya que es una mltiplicacion de areas
#ambas demuestran el cambio que hacen en el espacio no importa como se calculen los determinantes.

[[ 1 -1]
 [ 0  2]]
[[1 0]
 [1 1]]
2.0
2.0
True
