In [19]:
import numpy as np
import math  


In [20]:
A=np.array([[0,1],[1,1]])
print(A)

[[0 1]
 [1 1]]


In [35]:
A_2=A.dot(A).dot(A).dot(A).dot(A).dot(A).dot(A)
print(A_2)

[[ 8 13]
 [13 21]]


In [23]:
matriz_propia=np.array([[2,2],[1+math.sqrt(5),1-math.sqrt(5)]])
print(matriz_propia)

[[ 2.          2.        ]
 [ 3.23606798 -1.23606798]]


In [33]:
np.set_printoptions(suppress=True)
m_p_i= np.linalg.inv(matriz_propia)
A_propio=m_p_i.dot(A).dot(matriz_propia)
print(A_propio)

[[ 1.61803399 -0.        ]
 [ 0.         -0.61803399]]


In [39]:
A_propio2=A_propio.dot(A_propio).dot(A_propio).dot(A_propio).dot(A_propio).dot(A_propio).dot(A_propio)
print(A_propio2)

[[29.03444185 -0.        ]
 [ 0.         -0.03444185]]


In [40]:
A_3= matriz_propia.dot(A_propio2).dot(m_p_i)
print(A_3)

[[ 8. 13.]
 [13. 21.]]
