In [2]:
import numpy as np

In [3]:
M1 = np.array([[1,-2],
               [1,0]
              ])
print(M1)

[[ 1 -2]
 [ 1  0]]


In [4]:
M2 = np.array([[0,2],
               [1,0]
              ])
print(M2)

[[0 2]
 [1 0]]


In [6]:
 print(M2.dot(M1))

[[ 2  0]
 [ 1 -2]]


In [4]:
A=np.array([[-1,1],[-2,1],[3,1]])
print(A)

[[-1  1]
 [-2  1]
 [ 3  1]]


In [9]:
A_pinv= np.linalg.pinv(A)
b=np.array([[4],[5],[6]])
print(A_pinv)

[[-0.07142857 -0.14285714  0.21428571]
 [ 0.33333333  0.33333333  0.33333333]]


In [11]:
print(A_pinv.dot(b))

[[0.28571429]
 [5.        ]]


In [12]:
A= np.array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
A_pinv= np.linalg.pinv(A)
print(A_pinv)

[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
