In [1]:
# Descomponer una matriz: Quiere decir encontrar dos o más matrices que me ayuden a escribir la matriz original y 
# que tengan ciertas propiedades.
# Una matriz A la podemos escribir como: sus autovectores producto punto una matriz diagonal,
#     donde la matriz diagonal tiene todos los autovalores encontrados,
#     producto punto la matriz inversa de sus autovectores.
#### comentarios
# la matriz de autovectores que devuelve eig es una matriz ortogornal, por eso cumple la propiedad que utiliza en el minuto 7

In [3]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://static.platzi.com/media/user_upload/descomposicion_matrices_1-a1d5f87a-5432-4fac-b3b9-ffe61de66ac1.jpg")

In [1]:
import numpy as np

In [2]:
A = np.array([
    [3,2],
    [4,1]])
print(A)

[[3 2]
 [4 1]]


In [3]:
autovalores, autovectores = np.linalg.eig(A) #sacamos los autovalores y autovectores de la matriz A

In [4]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [6]:
#np.diag(autovalores)  genera una matriz diagonal con el vector que le entregemos, ene ste caso los autovalores
#np.linalg.inv(autovectores) entrega la inversa, recordar que para esto la matriz debe ser cuadrada
A_calculada = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [7]:
print(A_calculada)#vemos que nos devuelve la misma matriz que teniamos antes

[[3. 2.]
 [4. 1.]]


In [8]:
#### si la matriz es real y simetrica se pueden hacer otras descomposiciones
#simetrica =  A=A_transpuesta
A = np.array([
    [3,2],
    [2,3]
])
#verificamos q esta matriz es simetrica 
print( A == A.T)

[[ True  True]
 [ True  True]]


In [9]:
#calculamos de nuevo autovalores y autovectores
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [10]:
#vemos que podemos reescribirla igual q la anterior
# para este caso podemos descomponer esta matriz como A= V.diagonal(lambdas).V.T
# V= matriz de vectores propios o autovectores
#lambdas= autovalores
#V.T = la transpuesta de la matriz de autovectores
#recordar que computar la transpuesta es mas sencillo que computar una inversa
A_calculada =  autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calculada) #vemos que se cumple y tenemos los valores iniciales

[[3. 2.]
 [2. 3.]]
