In [1]:
#SVD o UDV
#es una forma de descomponer una matriz no cuadrada
#la matriz se divide en 3 U,D,V
# U y V son ortogonales
# D es una matriz diagonal con los valores singulares
# V tiene los vectores derechos singulares 
# U tiene los vectores izquierdos singulares
# estas matrices no tienen por que tener las mismas dimensiones
# la diagonal podria ser no cuadrada
# los vectores y matrices pueden ser pensados como subtransformaciones del espacio
#si tenemos una matriz de 3x2 se podria decir que estamos transformando un espacio de R3 y convertirlo a R2
# es decir estamos condensando informacion del tercer eje dentro de los unicos 2 ejes q vamos a conservar

In [3]:
import numpy as np

In [4]:
A = np.array([
    [1,2,3],
    [3,4,5]
])
print(A)

[[1 2 3]
 [3 4 5]]


In [5]:
U , D, V = np.linalg.svd(A)

In [6]:
print(U)

[[-0.46410668  0.88577931]
 [-0.88577931 -0.46410668]]


In [7]:
print(D) #la funcion nos entrega un vector para ahorrar espacio 

[7.97638869 0.61418515]


In [8]:
print(np.diag(D))# aqui acomodamos el vector de los valores singulares en una matrz diagonal

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [9]:
print(V)

[[-0.39133557 -0.5605708  -0.72980603]
 [-0.8247362  -0.13817999  0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


In [18]:
#para volver a la matriz original hay q agregar columnas de 0 a la matriz D para que quede dentro de las dimensiones que se 
#puedan operar
#para este caso U es 2x2, D es de 2x2, y V es de 3x3. Entonces tenemos que volver D de 2X3 para que se puedan operar 

In [31]:
vector_ceros = np.zeros((2,1))
matriz_D = np.concatenate((np.diag(D),vector_ceros),axis =1)
print(matriz_D)

[[7.97638869 0.         0.        ]
 [0.         0.61418515 0.        ]]


In [33]:
#ahora comprobamos 
Matriz_reconstruida = U.dot(matriz_D).dot(V)
print(Matriz_reconstruida)#vemos que si se cumple

[[1. 2. 3.]
 [3. 4. 5.]]


In [35]:
#########comentario op
#Hice esta pequeña funcion para comprobar con matrices aleatorias
# la descomposicion por valores singulares.
# En la función verifico que las dimensiones de las matrices concuerden para realizar la operacion,
# y si no es asi, les agrego las columnas extras para que coincidan. La dejo aqui por si quieren practicar tambien

# Matrices aleatorias:


[[3 1 4 2]
 [2 1 3 2]
 [3 4 3 4]]


In [66]:
# Descomposicion:
def SVD(A):
    U,D,V = np.linalg.svd(A)
    D = np.diag(D)
    if D.shape[1] != V.shape[0]:
        n_columns = np.abs(D.shape[0]-V.shape[0])
        extend = np.zeros(( D.shape[0] , n_columns ))
        D = np.append(D, extend, axis=1)# tambien se puede usar la funsion concatenate
    
    return U,D,V

In [67]:
B = np.random.randint(1,5, size=(3,4))# crea una matriz con valores random de forma 3,4
print(B)
U,D,V = SVD(B)
print(U)
print(D)
print(V)

[[4 2 2 3]
 [2 1 4 4]
 [4 4 3 2]]
[[-0.55017495  0.13113548  0.82468843]
 [-0.54684223 -0.80295078 -0.23713629]
 [-0.63108724  0.58144091 -0.51347382]]
[[10.20356146  0.          0.          0.        ]
 [ 0.          2.98803025  0.          0.        ]
 [ 0.          0.          1.39964597  0.        ]]
[[-0.57026492 -0.40883187 -0.50776198 -0.49983217]
 [ 0.41646299  0.59741156 -0.40334579 -0.55404889]
 [ 0.55055769 -0.45844073 -0.59985866  0.35621329]
 [-0.44524457  0.51554634 -0.46867849  0.56241419]]


In [68]:
Matriz_reconstruida = U.dot(D).dot(V)
print(Matriz_reconstruida)#vemos que si se cumple

[[4. 2. 2. 3.]
 [2. 1. 4. 4.]
 [4. 4. 3. 2.]]
